
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEDIVIDE LPAREN MINUS NUMBER PLUS RPAREN TIMESexpression : expression PLUS term\n                  | expression MINUS term\n                  | termterm : term TIMES factor\n            | term DIVIDE factor\n            | factorfactor : NUMBER\n              | LPAREN expression RPAREN\n              | factor LPAREN expression RPAREN'
    
_lr_action_items = {'NUMBER':([0,5,6,7,8,9,10,],[4,4,4,4,4,4,4,]),'LPAREN':([0,3,4,5,6,7,8,9,10,14,15,17,18,],[5,10,-7,5,5,5,5,5,5,10,10,-8,-9,]),'$end':([1,2,3,4,12,13,14,15,17,18,],[0,-3,-6,-7,-1,-2,-4,-5,-8,-9,]),'PLUS':([1,2,3,4,11,12,13,14,15,16,17,18,],[6,-3,-6,-7,6,-1,-2,-4,-5,6,-8,-9,]),'MINUS':([1,2,3,4,11,12,13,14,15,16,17,18,],[7,-3,-6,-7,7,-1,-2,-4,-5,7,-8,-9,]),'RPAREN':([2,3,4,11,12,13,14,15,16,17,18,],[-3,-6,-7,17,-1,-2,-4,-5,18,-8,-9,]),'TIMES':([2,3,4,12,13,14,15,17,18,],[8,-6,-7,8,8,-4,-5,-8,-9,]),'DIVIDE':([2,3,4,12,13,14,15,17,18,],[9,-6,-7,9,9,-4,-5,-8,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,5,10,],[1,11,16,]),'term':([0,5,6,7,10,],[2,2,12,13,2,]),'factor':([0,5,6,7,8,9,10,],[3,3,3,3,14,15,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression','parser_calculadora.py',37),
  ('expression -> expression MINUS term','expression',3,'p_expression','parser_calculadora.py',38),
  ('expression -> term','expression',1,'p_expression','parser_calculadora.py',39),
  ('term -> term TIMES factor','term',3,'p_term','parser_calculadora.py',46),
  ('term -> term DIVIDE factor','term',3,'p_term','parser_calculadora.py',47),
  ('term -> factor','term',1,'p_term','parser_calculadora.py',48),
  ('factor -> NUMBER','factor',1,'p_factor','parser_calculadora.py',55),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor','parser_calculadora.py',56),
  ('factor -> factor LPAREN expression RPAREN','factor',4,'p_factor','parser_calculadora.py',57),
]
